### ISSUE TITLE
你好，请问是怎么实现NBVP和AEP的开源代码在FUEL的仿真环境下运行的啊？

### ISSUE THREAD

**Issue by ziyu1018** [Zyhlibrary/FAEP#1]
还有就是轨迹对比是怎么画在一个图上的啊，先谢谢了

**Comment by Zyhlibrary** [comment]
我们是这么做的，可以提供参考一下。你可以只启动FUEL的仿真部分（不启动算法部分），然后将NBVP和AEP的数据源替换为FUEL仿真的深度图数据，并将前两者的实时定位数据反馈给FUEL的环境仿真，这样就可以用FUEL的仿真环境了。轨迹对比的话，你可以把每种算法的飞行轨迹记录下来，比如path.txt，我们的代码中已经有相关部分（搜索path.txt），你可以更改一下保存位置，然后就可以得到一个飞行轨迹文件。然后后面单独写一个函数，去同时在场景中显示这四条轨迹，具体可以使用visualization->drawlines()这个函数。
如果你觉得我们的代码有帮助的话，麻烦请帮我们点个Star谢谢啦~

**Comment by ziyu1018** [comment]
十分感谢！！！也谢谢你们开源代码，祝成果多多~
