### ISSUE TITLE
你好，我在运行的过程中经常出现Stack trace卡挺的情况....没法继续探索..

### ISSUE THREAD

**Issue by ziyu1018** [Zyhlibrary/FAEP#2]
应该是和线程相关，您遇到过这种情况吗？

**Comment by Poaos** [comment]
我运行FAEP也经常遇到该问题，特别是当我把探索地图改大一点的时候，基本上每次运行一会都会崩掉。前往您是怎么解决问题的哇？

**Comment by ziyu1018** [comment]
> 我运行FAEP也经常遇到该问题，特别是当我把探索地图改大一点的时候，基本上每次运行一会都会崩掉。前往您是怎么解决问题的哇？

我我也没有解决.....也是大场景就不行了....

**Comment by Poaos** [comment]
> > 我运行FAEP也经常遇到该问题，特别是当我把探索地图改大一点的时候，基本上每次运行一会都会崩掉。前往您是怎么解决问题的哇？
> 
> 我我也没有解决.....也是大场景就不行了....

我最近测试发现，那个报错应该 fast_exploration_fsm.cpp 中的线程，`t1 = std::thread(&FastExplorationFSM::new_thread, this);` 导致的，我尝试将多线程中的回调函数 cmdCallback(); 放到FSMCallback()函数末尾，在跑一个很大很大的地图过程中都没有死掉，不过这样的代价就是【探索过程明显变慢，没有以前流畅了】
