### ISSUE TITLE
planner_manager运行报错

### ISSUE THREAD

**Issue by ganshanliushui678** [Zyhlibrary/FAEP#3]
您好！我在运行您的代码的时候，在faep_manager/plan_manage/src/fast_exploration_manager.cpp的105行那里，有一条语句运行时我一直会报错，即planner_manager_->planYawForYawing(yaw, yaw1, true, ep_->relax_time_, circle_t);在我看来yaw(0)和yaw1的差值的绝对值是2pi，但在调用planYawForYawing时，也就是在faep_manager/plan_manage/src/planner_manager.cpp的1156行定义的planYawForYawing里，在1199行要判断start_yaw3d[0]和end_yaw3d[0]的差值绝对值，但两者差值的绝对值为2pi，大于pi，因此会报“Yaw change rapidly！”的错误。请问您有遇到过这个问题吗?或者是我理解的有误。

**Comment by QiangXc** [comment]
你好，有解决这个问题吗

**Comment by QiangXc** [comment]
哥们想必用的是20.04吧，问题已解决，参照FUEL里说的，需要把CMakeLists里C++11改为14；手动安装Nlopt同时更改CMakeLists；同时路径搜索这里也要改一下
![image](https://github.com/Zyhlibrary/FAEP/assets/88778564/33185a3e-b9de-4b49-aa6b-68804e12dda6)

**Comment by ganshanliushui678** [comment]
> 哥们想必用的是20.04吧，问题已解决，参照FUEL里说的，需要把CMakeLists里C++11改为14；手动安装Nlopt同时更改CMakeLists；同时路径搜索这里也要改一下 ![image](https://private-user-images.githubusercontent.com/88778564/287446261-33185a3e-b9de-4b49-aa6b-68804e12dda6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDExOTMsIm5iZiI6MTcwMjAwMDg5MywicGF0aCI6Ii84ODc3ODU2NC8yODc0NDYyNjEtMzMxODVhM2UtYjlkZS00YjQ5LWFhNmItNjg4MDRlMTJkZGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAyMDEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkOTg1ZGU3M2RhOGMwMWFjYjNlYWIzOWNjZTk3NjQ1NjExNzU3Yjg1NTllMTIwODRkMWRhOTljM2YzNGMxZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tTb3YSf3xesoQ5GlLcb131voil73v8HRJSukUyo3qnA)哦可以了可以了，非常感谢，我使用FUEL的时候记得修改了这一步，但是在FAEP里忘记修改了，多谢！

**Comment by Zyhlibrary** [comment]
不好意思，前段时间很忙，刚看到issue。上面的朋友说的很对，在20.04环境下需要更高版本的C++支持，并且需要下载NLopt源码在本地编译，然后修改配置路径。感谢各位对代码的认可和支持。如果有其他问题可以再及时交流。如果代码对各位有帮助的话，麻烦点个Star hahaha~.

**Comment by lovedreamms** [comment]
> 手动安装Nlopt同时更改CMakeLists

大佬您好，想请问一下更改CMakeLists，应该怎么书写呢

**Comment by ganshanliushui678** [comment]
> > 手动安装Nlopt同时更改CMakeLists
> 
> 大佬您好，想请问一下更改CMakeLists，应该怎么书写呢

把那个CMakeLists里边加入set(CMAKE_CXX_STANDARD 14)应该就可以了

**Comment by ganshanliushui678** [comment]
> > 手动安装Nlopt同时更改CMakeLists
> 
> 大佬您好，想请问一下更改CMakeLists，应该怎么书写呢
把那个CMakeLists里边加入set(CMAKE_CXX_STANDARD 14)应该就可以了

**Comment by ganshanliushui678** [comment]
> > 手动安装Nlopt同时更改CMakeLists
> 
> 大佬您好，想请问一下更改CMakeLists，应该怎么书写呢

把那个CMakeLists里边加入set(CMAKE_CXX_STANDARD 14)应该就可以了
