### ISSUE TITLE
请问文章里实验部分的图数据是怎么出的 ？

### ISSUE THREAD

**Issue by Renaissnance** [Zyhlibrary/FAEP#6]
实验数据中完成的覆盖率，覆盖了多大的面积这种话题我看代码里面是不包含在内的，请问文章里的实验数据如何的出的？
非常期待您的回复
![1111111111111111jpg](https://github.com/user-attachments/assets/79067f9e-6c84-4730-8a33-3e873ba278e2)

**Comment by Zyhlibrary** [comment]
不好意思刚看到提醒。代码里面已经提供了覆盖面积计算部分，你可以在代码里面搜索coverage.txt，然后将该路径修改为你自己本地的路径就行。完成探测任务后，查看该文件就可以获得探测面积的变化。希望对你有所帮助

**Comment by Renaissnance** [comment]
好的 感谢您 帮了很大忙

**Comment by Zyhlibrary** [comment]
> 好的 感谢您 帮了很大忙

小事，如果觉得论文和代码还可以且有帮助的话，麻烦引用推荐给更多的人，感谢

**Comment by Renaissnance** [comment]
![image](https://github.com/user-attachments/assets/b2c42992-5ffc-453b-92e9-eef6e873ec79)
![image](https://github.com/user-attachments/assets/d4638257-434b-4b8e-9a27-bde8dd188cc6)

作者您好 我在编译您的代码时碰到了函数未声明的报错 期待您的回复

**Comment by Zyhlibrary** [comment]
> ![image](https://private-user-images.githubusercontent.com/129180609/362515953-b2c42992-5ffc-453b-92e9-eef6e873ec79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDExOTcsIm5iZiI6MTcyNDkwMDg5NywicGF0aCI6Ii8xMjkxODA2MDkvMzYyNTE1OTUzLWIyYzQyOTkyLTVmZmMtNDUzYi05MmU5LWVlZjZlODczZWM3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwMzA4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2M0YjUzYmI3YjQ2OTI4NDJhMzBlZDY3MTljZjcwNjFkOGZmYjIwYWFmZjRmY2I2ODU2YzZhZjY5NTY1ZDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ImZK_zbRMkxm0dyHFQpW6wzo9glhoW57zpy7Hqd6pGg) ![image](https://private-user-images.githubusercontent.com/129180609/362516164-d4638257-434b-4b8e-9a27-bde8dd188cc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDExOTcsIm5iZiI6MTcyNDkwMDg5NywicGF0aCI6Ii8xMjkxODA2MDkvMzYyNTE2MTY0LWQ0NjM4MjU3LTQzNGItNGI4ZS05YTI3LWJkZThkZDE4OGNjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwMzA4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGRiYjI3MDU1NzU4MWY2ZTkxZDg3MjM3MTc3NjAwM2UzMWIwYzU3Y2Y1NGE2YzI1NGUwNjYzM2JiMzAxNGVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7Au-dTZ659WDNMrd022rdCCdPs8eBkUgmMyYgps9JNM)
> 
> 作者您好 我在编译您的代码时碰到了函数未声明的报错 期待您的回复

这应该不是我的代码吧，看样子像是周博士的集群探测代码
