### ISSUE TITLE
Yaw change rapidly!

### ISSUE THREAD

**Issue by LiiiiPeggy** [Zyhlibrary/FAEP#7]
Hello, after completing the compilation, I encountered the following bug when clicking on '2D Nav Goal' to trigger exploration. Could you please advise on how to resolve this issue?

[ INFO] [1729010070.245351994]: [FSM]: state: WAIT_TRIGGER
Triggered!
[triggerCallback]: from WAIT_TRIGGER to YAWING
[ WARN] [1729010070.349139029]: YAWING.
7.2
dt_yaw: 0.6, start yaw: 0 0 0, end: 6.28319
debug rapid change of yaw
6.28319
06.28319
[ERROR] [1729010070.349209215]: Yaw change rapidly!
start yaw: 0, 6.28319
[exploration_node-1] process has died [pid 15866, exit code -11, cmd /home/lqp/codes/FAEP_ws/devel/lib/exploration_manager/exploration_node /odom_world:=/state_ukf/odom /map_ros/pose:=/pcl_render_node/sensor_pose /map_ros/depth:=/pcl_render_node/depth /map_ros/cloud:=/pcl_render_node/cloud __name:=exploration_node __log:=/home/lqp/.ros/log/4dcebb52-8b13-11ef-8ffb-4d244ed3454f/exploration_node-1.log].
log file: /home/lqp/.ros/log/4dcebb52-8b13-11ef-8ffb-4d244ed3454f/exploration_node-1*.log

**Comment by LiiiiPeggy** [comment]
I am using Ubuntu 20.04 with PCL version 1.10.0. To accommodate this, I have added the following to my CMakeLists.txt:

ADD_COMPILE_OPTIONS(-std=c++11)
ADD_COMPILE_OPTIONS(-std=c++14)
set(CMAKE_CXX_FLAGS "-std=c++11 -O3")
find_package(PCL REQUIRED)
include_directories(
    ${PCL_INCLUDE_DIRS}
    CalibrationToolkit
    nodes/calibration_toolkit
    ${catkin_INCLUDE_DIRS}
    ${LIBXML2_INCLUDE_DIR}
    ${OpenCV_INCLUDE_DIRS}
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${CMAKE_CURRENT_BINARY_DIR}
    ${GLUT_INCLUDE_DIRS}
)

I’m not sure if any of these settings could be causing the bug. Could you please provide any insights?

**Comment by LiiiiPeggy** [comment]
I sincerely apologize for any inconvenience. I am not very familiar with GitHub operations. I found a solution in another closed issue: [Issue #3](https://github.com/Zyhlibrary/FAEP/issues/3).

**Comment by Zyhlibrary** [comment]
> I sincerely apologize for any inconvenience. I am not very familiar with GitHub operations. I found a solution in another closed issue: [Issue #3](https://github.com/Zyhlibrary/FAEP/issues/3).

Happy to hear this! If the code is useful for your work, please kindly star this project and cite our paper.
